<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HVNYRR3" failures="0" tests="6" name="testng_course.TestAnnotations" time="101.891" errors="1" timestamp="2023-01-27T16:30:38 IST" skipped="0">
  <testcase classname="testng_course.TestAnnotations" name="invocationCount" time="9.834"/>
  <system-out/>
  <testcase classname="testng_course.TestAnnotations" name="invocationCount" time="9.143"/>
  <system-out/>
  <testcase classname="testng_course.TestAnnotations" name="invocationCount" time="11.846"/>
  <system-out/>
  <testcase classname="testng_course.TestAnnotations" name="invocationCount" time="12.358"/>
  <system-out/>
  <testcase classname="testng_course.TestAnnotations" name="invocationCount" time="8.703"/>
  <system-out/>
  <testcase classname="testng_course.TestAnnotations" name="invocationTimeOut" time="50.007">
    <error message="Method testng_course.TestAnnotations.invocationTimeOut() didn&#039;t finish within the time-out 50000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testng_course.TestAnnotations.invocationTimeOut() didn't finish within the time-out 50000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- invocationTimeOut -->
  <system-out/>
</testsuite> <!-- testng_course.TestAnnotations -->
